mod: zshrc_ubuntu

diff --git a/zsh/zshrc_ubuntu b/zsh/zshrc_ubuntu
--- a/zsh/zshrc_ubuntu
+++ b/zsh/zshrc_ubuntu
@@ -1,33 +1,38 @@
 # If you come from bash you might have to change your $PATH.
-# export PATH=$HOME/bin:/usr/local/bin:$PATH
+# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
 
-# Path to your oh-my-zsh installation.
-  export ZSH="/home/tianws/.oh-my-zsh"
+# Path to your Oh My Zsh installation.
+export ZSH="$HOME/.oh-my-zsh"
 
-# Set name of the theme to load. Optionally, if you set this to "random"
-# it'll load a random theme each time that oh-my-zsh is loaded.
-# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
+# Set name of the theme to load --- if set to "random", it will
+# load a random theme each time Oh My Zsh is loaded, in which case,
+# to know which specific one was loaded, run: echo $RANDOM_THEME
+# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
 ZSH_THEME="robbyrussell"
 
-# Set list of themes to load
-# Setting this variable when ZSH_THEME=random
-# cause zsh load theme from this variable instead of
-# looking in ~/.oh-my-zsh/themes/
-# An empty array have no effect
+# Set list of themes to pick from when loading at random
+# Setting this variable when ZSH_THEME=random will cause zsh to load
+# a theme from this variable instead of looking in $ZSH/themes/
+# If set to an empty array, this variable will have no effect.
 # ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )
 
 # Uncomment the following line to use case-sensitive completion.
 # CASE_SENSITIVE="true"
 
-# Uncomment the following line to use hyphen-insensitive completion. Case
-# sensitive completion must be off. _ and - will be interchangeable.
+# Uncomment the following line to use hyphen-insensitive completion.
+# Case-sensitive completion must be off. _ and - will be interchangeable.
 # HYPHEN_INSENSITIVE="true"
 
-# Uncomment the following line to disable bi-weekly auto-update checks.
-# DISABLE_AUTO_UPDATE="true"
+# Uncomment one of the following lines to change the auto-update behavior
+# zstyle ':omz:update' mode disabled  # disable automatic updates
+# zstyle ':omz:update' mode auto      # update automatically without asking
+# zstyle ':omz:update' mode reminder  # just remind me to update when it's time
 
 # Uncomment the following line to change how often to auto-update (in days).
-# export UPDATE_ZSH_DAYS=13
+# zstyle ':omz:update' frequency 13
+
+# Uncomment the following line if pasting URLs and other text is messed up.
+# DISABLE_MAGIC_FUNCTIONS="true"
 
 # Uncomment the following line to disable colors in ls.
 # DISABLE_LS_COLORS="true"
@@ -39,6 +44,9 @@ ZSH_THEME="robbyrussell"
 # ENABLE_CORRECTION="true"
 
 # Uncomment the following line to display red dots whilst waiting for completion.
+# You can also set it to another string to have that shown instead of the default red dots.
+# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
+# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
 # COMPLETION_WAITING_DOTS="true"
 
 # Uncomment the following line if you want to disable marking untracked files
@@ -57,17 +65,15 @@ ZSH_THEME="robbyrussell"
 # Would you like to use another custom folder than $ZSH/custom?
 # ZSH_CUSTOM=/path/to/new-custom-folder
 
-# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
-# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
+# Which plugins would you like to load?
+# Standard plugins can be found in $ZSH/plugins/
+# Custom plugins may be added to $ZSH_CUSTOM/plugins/
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
-plugins=(
-  git
-  zsh-autosuggestions
-  colored-man-pages
-  zsh-syntax-highlighting
-  z
-)
+# 先apt install fzf
+# Set up fzf key bindings and fuzzy completion
+# source <(fzf --zsh)
+plugins=(git colorize z zsh-autosuggestions zsh-syntax-highlighting vi-mode fzf)
 
 source $ZSH/oh-my-zsh.sh
 
@@ -82,75 +88,107 @@ source $ZSH/oh-my-zsh.sh
 # if [[ -n $SSH_CONNECTION ]]; then
 #   export EDITOR='vim'
 # else
-#   export EDITOR='mvim'
+#   export EDITOR='nvim'
 # fi
 
 # Compilation flags
-# export ARCHFLAGS="-arch x86_64"
+# export ARCHFLAGS="-arch $(uname -m)"
 
-# ssh
-# export SSH_KEY_PATH="~/.ssh/rsa_id"
-
-# Set personal aliases, overriding those provided by oh-my-zsh libs,
-# plugins, and themes. Aliases can be placed here, though oh-my-zsh
-# users are encouraged to define aliases within the ZSH_CUSTOM folder.
+# Set personal aliases, overriding those provided by Oh My Zsh libs,
+# plugins, and themes. Aliases can be placed here, though Oh My Zsh
+# users are encouraged to define aliases within a top-level file in
+# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
+# - $ZSH_CUSTOM/aliases.zsh
+# - $ZSH_CUSTOM/macos.zsh
 # For a full list of active aliases, run `alias`.
 #
 # Example aliases
 # alias zshconfig="mate ~/.zshrc"
 # alias ohmyzsh="mate ~/.oh-my-zsh"
 
-export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
-
-#my alise                                                                      
-alias sshx='ssh -X'
-alias setproxy="export ALL_PROXY=socks5://127.0.0.1:8606"
-alias unsetproxy="unset ALL_PROXY"
-alias sudomakeinstall="sudo make install>&LOG_install &"
-
-# #Powerline by tianws    
-# powerline-daemon -q     
-# POWERLINE_BASH_CONTINUATION=1
-# POWERLINE_BASH_SELECT=1 
-# . /usr/share/powerline/bindings/bash/powerline.sh
-                        
-#避免在ranger启动的shell内创建新的ranger
-rg() {                  
-    if [ -z "$RANGER_LEVEL" ]
-        then            
-            ranger      
-        else            
-            exit        
-        fi              
-}                       
-                        
-#避免ranger重复载入配置文件
-export RANGER_LOAD_DEFAULT_RC=FALSE
-
-export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}/usr/local/cuda/extras/CUPTI/lib64
-
-# unsetopt correct_all
-# unsetopt AUTO_CD
-# setopt noautomenu
-# setopt nomenucomplete
-
-## added by Miniconda3 4.5.12 installer
-# >>> conda init >>>
+# >>> conda initialize >>>
 # !! Contents within this block are managed by 'conda init' !!
-__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/tianws/opt/miniconda3/bin/conda' shell.bash hook 2> /dev/null)"
+__conda_setup="$('/home/tianws/opt/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
 if [ $? -eq 0 ]; then
-    \eval "$__conda_setup"
+    eval "$__conda_setup"
 else
     if [ -f "/home/tianws/opt/miniconda3/etc/profile.d/conda.sh" ]; then
         . "/home/tianws/opt/miniconda3/etc/profile.d/conda.sh"
-        CONDA_CHANGEPS1=false conda activate base
     else
-        \export PATH="/home/tianws/opt/miniconda3/bin:$PATH"
+        export PATH="/home/tianws/opt/miniconda3/bin:$PATH"
     fi
 fi
 unset __conda_setup
-# <<< conda init <<<
+# <<< conda initialize <<<
 
-alias dockerrun='docker run --runtime=nvidia -it --rm -u $(id -u):$(id -g) -v $(pwd):$(pwd) -w $(pwd) --name=seg segmentation-dependence'
+___MY_VMOPTIONS_SHELL_FILE="${HOME}/.jetbrains.vmoptions.sh"; if [ -f "${___MY_VMOPTIONS_SHELL_FILE}" ]; then . "${___MY_VMOPTIONS_SHELL_FILE}"; fi
+
+export NVM_DIR="$HOME/.nvm"
+[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
+[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
+
+# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
+export PATH="$PATH:$HOME/.rvm/bin"
+
+# apt install starship
+# 新建~/.config/starship.toml，写入一下以显示完整路径
+# [directory]
+# truncation_length=0
+# truncate_to_repo=false
+# 执行conda config --set changeps1 False 取消默认conda提示符
+eval "$(starship init zsh)"
+
+# Copy the contents of a file to the clipboard.
+#
+# copyfile <file_pathname>
+function copyfile {
+  cat $1 | pbcopy
+}
+
+# Copies the path of given directory or file to the clipboard.
+# Copy current directory if no parameter.
+function copypath {
+  # If no argument passed, use current directory
+  local file="${1:-.}"
+
+  # If argument is not an absolute path, prepend $PWD
+  [[ $file = /* ]] || file="$PWD/$file"
+
+  # Copy the absolute path without resolving symlinks
+  # If clipcopy fails, exit the function with an error
+  print -n "${file:a}" | pbcopy || return 1
+
+  echo ${(%):-"%B${file:a}%b copied to clipboard."}
+}
+
+function proxy {
+   proxy_host='127.0.0.1'
+   proxy_port=9050
+   http_proxy_url="http://$proxy_host:$proxy_port"
+   socks5_proxy_url="socks5://$proxy_host:$proxy_port"
+   export http_proxy=$http_proxy_url
+   export HTTP_PROXY=$http_proxy_url
+   export https_proxy=$http_proxy_url
+   export HTTPS_PROXY=$http_proxy_url
+   export all_proxy=$socks5_proxy_url
+   export ALL_PROXY=$socks5_proxy_url
+ }
+function unproxy {
+   unset http_proxy
+   unset HTTP_PROXY
+   unset https_proxy
+   unset HTTPS_PROXY
+   unset all_proxy
+   unset ALL_PROXY
+}
+alias ls='ls -F --color'
+alias grep='grep --color'
+alias mkdir='mkdir -pv'
+alias sshx='ssh -X'
+alias l='eza --classify --color-scale --icons=always --group-directories-first --time-style long-iso'
+alias ll='eza --classify --color-scale --icons=always --group-directories-first --time-style long-iso --long -a --show-symlinks'
+alias lsg='eza --classify --color-scale --icons=always --group-directories-first --time-style long-iso --git-ignore --git --git-repos'
+alias llg='eza --classify --color-scale --icons=always --group-directories-first --time-style long-iso --git-ignore --git --git-repos --long'
+alias llt='eza --classify --color-scale --icons=always --group-directories-first --time-style long-iso -l -a -a --show-symlinks --total-size'
 
 source /etc/zsh_command_not_found
